### ISSUE TITLE
Create a DAL/Controller for the the fs that is created during the github ap output 

### ISSUE THREAD

**Issue by Isan-Rivkin** [ofiriluz/octopus#2]
use @ofiriluz  fs controller. @ofiriluz whats the status of your controller? also could you post here a link to that api ?

**Comment by ofiriluz** [comment]
FS Controller is abit more mature now, it acts as a virtual filesystem from a given path and has quite a few helper functions
All of the controllers are generated from a controller pool which is a singleton in the application
Those controllers should be used within accessors or as a stabdalone

Example of generting:

```python
self.__fs_ctrl = AccessControllerPool().generate_access_controller(name='fs',
        base_path=workspace_path, create_base_path=False)
```
The name is an indication to a registered controller generator on the pool, others are kwargs to the fs controller itself

FS Controller:
https://github.com/ofiriluz/octopus/blob/master/octopus/data_access/controllers/fs_controller.py
